server {
    listen 80 default_server;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    include /etc/nginx/mime.types;

    gzip on;
    gzip_types application/wasm application/javascript text/html;

    location / {
        try_files $uri =404;
        add_header Cache-Control "no-cache";
    }
}
